DROP TABLE IF EXISTS GRAPH_TEST;
DROP TABLE IF EXISTS GRAPH_TEST_2;

CREATE TABLE GRAPH_TEST(src_id INT, dest_id INT, weight REAL);
CREATE TABLE GRAPH_TEST_2(src_id INT, dest_id INT, weight REAL);


INSERT INTO GRAPH_TEST VALUES(0, 1, 1);
INSERT INTO GRAPH_TEST VALUES(0, 2, 1);
INSERT INTO GRAPH_TEST VALUES(1, 2, 1);
INSERT INTO GRAPH_TEST VALUES(1, 3, 1);
INSERT INTO GRAPH_TEST VALUES(2, 3, 1);
INSERT INTO GRAPH_TEST VALUES(2, 5, 1);
INSERT INTO GRAPH_TEST VALUES(4, 1, 1);
INSERT INTO GRAPH_TEST VALUES(5, 2, 1);


INSERT INTO GRAPH_TEST_2
  SELECT src_id, dest_id, weight FROM GRAPH_TEST
  UNION
  SELECT dest_id AS src_id, src_id AS dest_id, weight FROM GRAPH_TEST;


SELECT * FROM GRAPH_TEST_2;

DROP TABLE IF EXISTS GRAPH_TEST;
DROP TABLE IF EXISTS GRAPH_TEST_2;
