DROP TABLE IF EXISTS TABLE_TEST;
DROP TABLE IF EXISTS TABLE_TEST_2;

CREATE TABLE TABLE_TEST(
  id INT PRIMARY KEY ,
  value INT);

CREATE TABLE TABLE_TEST_2(
  id INT PRIMARY KEY,
  value INT);

INSERT INTO TABLE_TEST VALUES(0, 1);
INSERT INTO TABLE_TEST VALUES(1, 2);

INSERT INTO TABLE_TEST_2 VALUES(1, 2);
INSERT INTO TABLE_TEST_2 VALUES(2, 1);


SELECT (COALESCE(A.value, 0) - COALESCE(B.value, 0)) AS diff
FROM TABLE_TEST AS A
FULL OUTER JOIN TABLE_TEST_2 AS B
ON A.id = B.id;

DROP TABLE TABLE_TEST;
DROP TABLE TABLE_TEST_2;
