DROP TABLE IF EXISTS MAT_TEST_1;
DROP TABLE IF EXISTS MAT_TEST_2;

CREATE TABLE MAT_TEST_1(row_id INT, col_id INT, value real);
CREATE TABLE MAT_TEST_2(row_id INT, col_id INT, value real);


INSERT INTO MAT_TEST_1 VALUES(0, 0, 1);
INSERT INTO MAT_TEST_1 VALUES(0, 1, 1);
INSERT INTO MAT_TEST_1 VALUES(0, 2, 1);

INSERT INTO MAT_TEST_1 VALUES(1, 0, 0);
INSERT INTO MAT_TEST_1 VALUES(1, 1, 0);
INSERT INTO MAT_TEST_1 VALUES(1, 2, 0);

INSERT INTO MAT_TEST_2 VALUES(0, 0, 0);
INSERT INTO MAT_TEST_2 VALUES(0, 1, 1);

INSERT INTO MAT_TEST_2 VALUES(1, 0, 0);
INSERT INTO MAT_TEST_2 VALUES(1, 1, 1);

INSERT INTO MAT_TEST_2 VALUES(2, 0, 0);
INSERT INTO MAT_TEST_2 VALUES(2, 1, 1);

SELECT A.row_id, B.col_id, sum(A.value * B.value)
FROM MAT_TEST_1 AS A INNER JOIN MAT_TEST_2 AS B
ON A.col_id = B.row_id
GROUP BY A.row_id, B.col_id;

DROP TABLE IF EXISTS MAT_TEST_1;
DROP TABLE IF EXISTS MAT_TEST_2;
