DROP TABLE IF EXISTS VECTOR_TEST_1;
DROP TABLE IF EXISTS VECTOR_TEST_2;

CREATE TABLE VECTOR_TEST_1(
  id INT PRIMARY KEY NOT NULL,
  value real NOT NULL);

CREATE TABLE VECTOR_TEST_2(
  id INT PRIMARY KEY NOT NULL,
  value real NOT NULL);


INSERT INTO VECTOR_TEST_1 VALUES(0, 1);
INSERT INTO VECTOR_TEST_1 VALUES(1, 2);
INSERT INTO VECTOR_TEST_1 VALUES(2, 3);

INSERT INTO VECTOR_TEST_2 VALUES(0, 3);
INSERT INTO VECTOR_TEST_2 VALUES(1, 2);
INSERT INTO VECTOR_TEST_2 VALUES(2, 1);

SELECT sum(VECTOR_TEST_1.value * VECTOR_TEST_2.value) AS Dotproduct
FROM VECTOR_TEST_1 INNER JOIN VECTOR_TEST_2
ON VECTOR_TEST_1.id = VECTOR_TEST_2.id;


DROP TABLE IF EXISTS VECTOR_TEST_1;
DROP TABLE IF EXISTS VECTOR_TEST_2;
